import type { NextPage } from 'next';
import Head from 'next/head';

// import styles from '../styles/Home.module.scss';
// import 'bootstrap/dist/css/bootstrap.min.css';
import Header from '@/molecules/Header';
import { Item } from '@/types/HeaderProps';

const menu:Item[] = [
	{ name: 'My 지출 관리', path: '/ji' },
	{ name: 'My 저축 관리', path: '/ju' },
	{ name: 'My 구독 관리', path: '/gu' }
];

const Home: NextPage = () => (
	// <div className={styles.container}>
	<div>
		<Head>
			<title>Create Next App</title>
			<meta content='Generated by create next app' name='description' />
			<link href='/favicon.ico' rel='icon' />
		</Head>
		<Header items={menu} />
	</div>
);

export default Home;