import type { NextPage } from 'next';
import Head from 'next/head';

// import styles from '../styles/Home.module.scss';
// import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from '@/layout/NavBar';

const Home: NextPage = () => (
	// <div className={styles.container}>
	<div>
		<Head>
			<title>Create Next App</title>
			<meta content='Generated by create next app' name='description' />
			<link href='/favicon.ico' rel='icon' />
		</Head>
		<NavBar />
	</div>
);

export default Home;